name: Tests

on: [push, pull_request]

jobs:
    test:
        runs-on: ubuntu-latest
        name: PHP ${{ matrix.php }} - Laravel ${{ matrix.laravel }}

        strategy:
            fail-fast: true
            matrix:
                php: [ 8.2, 8.1, 8.0]
                laravel: [ 10.*, 9.*, 8.*]
                composer-flags: ["--prefer-lowest"]
                include:
                    - laravel: 10.*
                      testbench: 8.*
                    - laravel: 9.*
                      testbench: 7.*
                    - laravel: 8.*
                      testbench: 6.*
                exclude:
                    - laravel: 10.*
                      php: 8.0
                    - laravel: 10.*
                      php: 7.4
                    - laravel: 9.*
                      php: 7.4

            steps:
                - name: Checkout
                  uses: actions/checkout@v2

                - name: Setup PHP
                  uses: shivammathur/setup-php@v2
                  with:
                      php-version: ${{ matrix.php-version }}
                      coverage: pcov

                - name: Install dependencies
                  run: |
                      composer require "laravel/framework:${{ matrix.laravel }}" "orchestra/testbench:${{ matrix.testbench }}" --no-interaction --no-update
                      composer update --prefer-stable --prefer-dist --no-interaction --no-suggest

                - name: Run tests
                  run: ./vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover

                - name: Upload coverage to Scrutinizer
                  run: |
                      wget https://scrutinizer-ci.com/ocular.phar
                      php ocular.phar code-coverage:upload --format=php-clover coverage.clover
